import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { ArrowLeft, TrendingUp } from "lucide-react";

export default function TermsOfService() {
  const [, navigate] = useLocation();

  return (
    <div className="min-h-screen bg-background">
      <div className="border-b sticky top-0 bg-background/95 backdrop-blur z-50">
        <div className="max-w-4xl mx-auto px-4 py-3 flex items-center gap-3">
          <Button variant="ghost" size="icon" onClick={() => navigate("/")} data-testid="button-back">
            <ArrowLeft className="w-4 h-4" />
          </Button>
          <div className="flex items-center gap-2">
            <TrendingUp className="w-4 h-4 text-primary" />
            <span className="text-sm font-semibold">AI Market Audit</span>
          </div>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold mb-2" data-testid="text-terms-title">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-8">Last updated: March 2026</p>

        <div className="prose prose-sm max-w-none space-y-6 text-muted-foreground">
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">1. Service Description</h2>
            <p>AI Market Audit provides AI-powered marketing audits for websites. Our service uses 5 specialized AI agents to analyze publicly accessible website content and generate comprehensive marketing audit reports.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">2. Acceptable Use</h2>
            <p>By using our service, you agree to:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>Only submit URLs for websites you own or have authorization to audit.</li>
              <li>Provide accurate contact information (name and email).</li>
              <li>Not use the service to scrape, copy, or reproduce content from third-party websites for purposes other than receiving your audit report.</li>
              <li>Not attempt to circumvent payment requirements or access controls.</li>
              <li>Not use automated tools to submit excessive audit requests.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">3. Pricing and Payment</h2>
            <p>A free preview of audit results is available at no cost, including the overall marketing score, category breakdown, executive summary, and critical/high-severity findings.</p>
            <p className="mt-2">The full audit report is available for a one-time payment of $99 per audit. Payment is processed securely through Stripe. Each audit is a separate purchase -- there are no subscriptions or recurring charges.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">4. AI-Generated Content</h2>
            <p>Our audit reports are generated by AI models and should be treated as automated analysis, not professional consulting advice. While our AI agents are trained on marketing best practices and industry standards, results may vary in accuracy and applicability. We recommend using audit findings as a starting point for your marketing strategy, supplemented by human expertise when making significant business decisions.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">5. Service Limitations</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>We can only analyze publicly accessible website content.</li>
              <li>Results depend on the website being reachable at the time of the audit.</li>
              <li>Some websites may block automated access, which can affect audit quality.</li>
              <li>AI analysis reflects best practices at the time of the audit and may not account for industry-specific nuances.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">6. Intellectual Property</h2>
            <p>Upon purchase, you receive a license to use your audit report for internal business purposes, share it with team members or clients, and implement the recommended changes. You may not resell audit reports as your own product or service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">7. Limitation of Liability</h2>
            <p>AI Market Audit is provided "as is" without warranties of any kind. We are not liable for any business decisions made based on audit recommendations, indirect or consequential damages arising from use of the service, or website performance changes resulting from implementing audit findings.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">8. Changes to Terms</h2>
            <p>We may update these Terms of Service from time to time. Continued use of the service after changes constitutes acceptance of the revised terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">9. Contact</h2>
            <p>For questions about these Terms, contact us at <a href="mailto:support@aimarketaudit.com" className="text-primary hover:underline">support@aimarketaudit.com</a>.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
